[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CircuitPython_OPT4001"
authors = [{name = "Thomas Damiani", email = "tdamiani@andrew.cmu.edu"}]
dynamic = ["0.1.0", "CircuitPython driver for the OPT4001 ambient light sensor"]